admin:
    resource: "@AdminBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: @AppBundle/Controller/
    type:     annotation

_security_login:
    pattern:  /admin/login
    defaults: { _controller: AppBundle:Auth:login }

login_check:
    path: /admin/login_check

_security_logout:
    pattern:  /admin/logout

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

gregwar_captcha_routing:
    resource: "@GregwarCaptchaBundle/Resources/config/routing/routing.yml"