#jms_security_extra:
#    secure_all_services: false
#    expressions: true

security:
    encoders:
        AppBundle\Entity\User:
            algorithm: sha512
            encode-as-base64: true
            iterations: 10

    role_hierarchy:
        ROLE_OPERATOR: [ROLE_USER]
        ROLE_ADMIN: [ROLE_OPERATOR]

    providers:
        main:
            entity: { class: AppBundle:User, property: username }

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/
            provider: main
            form_login:
                login_path: /login
                check_path: /login_check
                failure_path: /
            logout:
                path:   /logout
                target: /
            anonymous: ~

#        admin:
#            pattern: ^/admin/
#            provider: main
#            form_login:
#                check_path: /admin/login_check
#                login_path: /admin/login
#                use_referer: true
#            logout:
#                path:   /admin/logout
#                target: /
#            security: true
#            anonymous: true

    access_control:
        - { path: /.*, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, role: ROLE_OPERATOR }
